zowe/explorer-mvs

- README.md
> update npm registry to release not local release

- WebContent/js/components/explorer/TreeDatasetMember.js
- tests/component/TreeDataSetMember.js
> use refactored name for get dataset and member

- WebContent/js/reducers/treeDS.js
> when invalide children action created set isFetching to false

- package.json
Signed-off-by: Colin-Stone <30794003+Colin-Stone@users.noreply.github.com>
> Include the API mediation version of editor

- WebContent/js/components/editor/Editor.js
> Ensure content is not null and not still fetching

- WebContent/css/styles.css
- WebContent/js/components/explorer/TreeDataset.js
- WebContent/js/components/explorer/TreeDatasetMember.js
- WebContent/js/containers/DatasetTree.js
- WebContent/js/containers/FullHeightTree.js
- package-lock.json
> better use of available space in tree

- WebContent/js/components/editor/Editor.js
- package-lock.json
- package.json
> pass editorReady callback function to dispatch the fetch content

- package.json
Signed-off-by: Colin-Stone <30794003+Colin-Stone@users.noreply.github.com>
> Version increment

- WebContent/js/components/dialogs/AtlasDialog.js
- WebContent/js/components/dialogs/datasets/CreateDatasetDialog.js
- WebContent/js/components/dialogs/datasets/DatasetSaveAsDialog.js
- package.json
> Add auto scroll y to body of dialogs to stop content being hidden

- WebContent/js/containers/DatasetTree.js
- package.json
> Sort datasets array before rendering treeDataset components

- Jenkinsfile
> release with tagging and versioning

- WebContent/js/actions/editor.js
- tests/actions/TestEditor.js
https://github.com/zowe/explorer-mvs/issues/63
> added check fail notification when dataset load returns error

- package.json
> use newer ui server

- package.json
> bump explorer ui server version

- dco_signoffs/Colin Stone-explorer-mvs.txt
Signed-off-by: Colin-Stone <30794003+Colin-Stone@users.noreply.github.com>
> Colin Stone-DCO text

- WebContent/js/components/explorer/TreeDataset.js
- tests/actions/TestEditor.js
- tests/actions/TestTreeDatasets.js
- tests/testResources/actions/treeDS.js
- tests/testResources/reducers/treeDS.js
https://github.com/zowe/explorer-mvs/issues/92
Bug fix for pulling content for extended PS-*
> dsorg check to startsWith,  detect extended PS, PO

- README.md
> add info on new issue location

- scripts/explorer-mvs-configure.sh
Signed-off-by: stevenhorsman <steven@uk.ibm.com>
For https://github.com/zowe/zowe-install-packaging/issues/754
> Create iframe app in configure

- WebContent/js/components/editor/EditorMenuBar.js
> Use window.location to create fullscreen link

- scripts/explorer-mvs-start.sh
> Set node process title

- WebContent/js/actions/validation.js
- WebContent/js/components/dialogs/LoginDialog.js
- WebContent/js/utilities/urlUtils.js
- package.json
- tests/UnitTests/actions/TestValidation.js
- tests/UnitTests/testResources/hostConstants.js
> Switch over to v2 api calls and use SSO

- .github/pull_request_template.md
- CHANGELOG.md
- CONTRIBUTING.md
- README.md
> Add changelog, contributing and PR template, update readme too

- tests/FVTTests/DatasetTree/testSearchingForDatasets.ts
> Fast loading icon transition

- CHANGELOG.md
- README.md
- WebContent/js/index.js
- package-lock.json
- package.json
- pluginDefinition.json
- webpack.config.js
> Webpack logger changes

- Jenkinsfile
- package-lock.json
- package.json
- tests/FVTTests/DatasetInteration/testContextMenu.ts
- tests/FVTTests/DatasetTree/testInitialisationOfDatasetTree.ts
- tests/FVTTests/DatasetTree/testSearchingForDatasets.ts
- tests/FVTTests/PageLoad/testPageLoad.ts
- tests/FVTTests/README.md
- tests/FVTTests/environment.ts
- tests/FVTTests/testConfig.ts
> Update fvtutil uiserver

- package.json
- scripts/explorer-mvs-start.sh
This PR addresses Issue: https://github.com/zowe/explorer-ui-server/issues/35
- [x ] Bug fix
> rollback ui server breaking smpe build

- .pax/pre-packaging.sh
- package.json
- scripts/explorer-mvs-start.sh
Add keyring support back in and update build: https://github.com/zowe/zlux/issues/500
> Add keyring back

- CHANGELOG.md
This PR addresses Issue: Just updating change log
> add changleog for keyring support

- .pax/pre-packaging.sh
- .pax/prepare-workspace.sh
- CHANGELOG.md
- Jenkinsfile
- package-lock.json
- package.json
This PR addresses Issue: https://github.com/zowe/explorer-ui-server/issues/38
> fix packaging ui server tagging

- CHANGELOG.md
- WebContent/js/components/Announcer.js
- WebContent/js/containers/DatasetTree.js
This PR addresses Issue:Related issue... https://github.com/zowe/zlux/issues/484
> Fix announcer taking up space and incorrect offset

- CHANGELOG.md
- scripts/explorer-mvs-start.sh
This PR addresses Issue: https://github.com/zowe/explorer-ui-server/issues/44
> add default CSP value start.sh

- CHANGELOG.md
- WebContent/js/components/editor/Editor.js
- WebContent/js/components/editor/EditorMenuBar.js
- WebContent/js/reducers/editor.js
- tests/UnitTests/reducers/TestEditor.js
- tests/UnitTests/testResources/reducers/editor.js
This PR addresses Issue: [https://github.com/zowe/zlux/issues/291]
> Add loading icon to dataset content fetch

- tests/FVTTests/DatasetTree/testResizingOfDatasetTree.ts
This PR addresses Issue: skipping resize test flaky on jenkins, though pass fine on local
FYI @skurnevich
As seen here:
https://wash.zowe.org:8443/view/Explorers/job/explorer-mvs/view/change-requests/job/PR-152/
> skip resize test

- scripts/explorer-mvs-start.sh
Part of fixes to fulfill https://github.com/zowe/zowe-install-packaging/issues/1702.
Branch build has been embedded into a Zowe test build https://wash.zowe.org:8443/view/Zowe/job/zowe-install-packaging/job/users%252Fjack%252Fzwelnch/3/consoleFull and passed these tests:
- convenience build: https://wash.zowe.org:8443/view/Zowe/job/zowe-install-test/job/users%252Fjack%252Fzwelnch/4/
- smpe ptf: https://wash.zowe.org:8443/view/Zowe/job/zowe-install-test/job/users%252Fjack%252Fzwelnch/5/
> trap int signal

- Jenkinsfile
- scripts/prepare-fvt.sh
Signed-off-by: stevenhorsman <steven@uk.ibm.com>
Part of zowe/zowe-install-packaging/issues/1692
- Update to pick up renamed version of files-api
> Update artifactory path for files api component

- .pax/prepare-workspace.sh
- CHANGELOG.md
- bin/prepare-fvt.sh
- bin/start.sh
- manifest.yaml
- pluginDefinition.prod.json
- update manifest to include appfw plugin
- add new pluginDefinition tempalte with destination property
- changed packaging from app to web folder
This PR addresses Issue: https://github.com/zowe/zlux/issues/558
> update packaging, manifest, add pluginDef template

- .pax/pre-packaging.sh
- .pax/prepare-workspace.sh
https://github.com/zowe/zowe-install-packaging/issues/1902
> exclude png, tag content

- .github/workflows/explorer-mvs-images.yml
- bin/start.sh
- container/.gitignore
- container/Dockerfile
- container/README.md
- container/prepare.sh
This PR is part of https://github.com/zowe/zowe-install-packaging/issues/2241
> define mvs image

- .github/workflows/build_test.yml
> add validate-package-json as dedicated step

- .github/workflows/build_test.yml
> move validate-package-json to separated job

- tests/FVTTests/DatasetTree/testSearchingForDatasets.ts
Signed-off-by: Adarshdeep Cheema <adarshdeep.cheema@ibm.com>
> fix the refresh Icon transition testcase- intermediate failure

- package-lock.json
- package.json
Signed-off-by: Adarshdeep Cheema <adarshdeep.cheema@ibm.com>
This PR addresses Issue: https://github.com/zowe/security-reports/issues/93
> fixing the vunerability re nodejs-ajv

- WebContent/js/actions/validation.js
- tests/FVTTests/testConfig.ts
- tests/UnitTests/actions/TestValidation.js
- tests/UnitTests/testResources/actions/validation.js
> Fix apiml urls

- README.md
- package.json
Signed-off-by: Leanid Astrakou <lastrakou@rocketsoftware.com>
> Small readme update for up-to-date dev

- README.md
- WebContent/index.html
- package.json
> Update URLs to V2
